name: Send webhook message

on:
  schedule:
    - cron: '55 9,14,19,22 * * *'

jobs:
  webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Send webhooks
        env:
          WEBHOOK_URLS: ${{ secrets.WEBHOOK_URLS }}
        run: npm run sendhook
